import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL")
OPENAI_MODEL = os.getenv("OPENAI_MODEL")

MIN_CANDIDATES = int(os.getenv("MIN_CANDIDATES", 3))

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
